[project]
name = "fastrtc-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastrtc[stt,tts,vad]>=0.0.24",
    "langchain>=0.3.25",
    "langchain-ollama>=0.3.3",
    "python-dotenv>=1.1.0",
]
